### ISSUE TITLE
Gradle dependency not available?

### ISSUE THREAD

**Issue by stojan26** [1Jajen1/propCheck#6]
First the smaller issue - a typo in the readme:

`testImplementation: 'propCheck:propCheck-kt:0.9.3'`

the `:` should be removed.

Adding the maven repository and the gradle dependency (without `:`) I get the following error:

```
Execution failed for task ':compileTestKotlin'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find propCheck:propCheck-kt:0.9.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/propCheck/propCheck-kt/0.9.3/propCheck-kt-0.9.3.pom
       - https://jcenter.bintray.com/propCheck/propCheck-kt/0.9.3/propCheck-kt-0.9.3.jar
       - https://repo.maven.apache.org/maven2/propCheck/propCheck-kt/0.9.3/propCheck-kt-0.9.3.pom
       - https://repo.maven.apache.org/maven2/propCheck/propCheck-kt/0.9.3/propCheck-kt-0.9.3.jar
```

**Comment by 1Jajen1** [comment]
Its always `groupId:artifactId:version` right? I just tried it in a seperate project and it seems to work o.O

https://dl.bintray.com/jannis/propCheck-kt/propCheck/propCheck-kt/ lists 0.9.3 o.O Me is confused :confused:

**Comment by stojan26** [comment]
Yup should be `groupId:artifactId:version` - but somehow the location it looks for (`propCheck/propCheck-kt/0.9.3/`) doesn't match the location it on.

**Comment by 1Jajen1** [comment]
For me at work in a maven project this:
```
<dependency>
            <groupId>propCheck</groupId>
            <artifactId>propCheck-kt</artifactId>
            <version>0.9.3</version>
            <scope>test</scope>
</dependency>
```

works. Dunno if this is a weird gradle specific or something :/

**Comment by 1Jajen1** [comment]
Just got home and tested this in a gradle config (kotlin dsl, makes no difference tho). 
```
"compile"("propCheck:propCheck-kt:0.9.3")
```

and with repositories
```
maven {
    setUrl("https://dl.bintray.com/jannis/propCheck-kt/")
}
```

This definitly works for me. Can you share more of your build.gradle? I think the problem may be somewhere else.

**Comment by LordRaydenMK** [comment]
Hey @1Jajen1 thanks for trying to help.... (I created the issue with my company account, and comenting now with my personal one).

You are right, it works fine. 

Basically I added the repository at the wrong place, under `buildscript` and `repositories` instead of the top level `repositories`.

Sorry for the confusion and feel free to close the issue.

**Comment by 1Jajen1** [comment]
Great. Glad to hear that it works :)
